import {
  UserProfile,
  Shop,
  Product,
  StallLocation,
  SchoolHoliday,
  Announcement,
  Order,
  MerchantFeeRecord,
  SystemSettings,
  ShopReview,
} from '@/types';

export const initialUserProfile: UserProfile = {
  id: 'user_student_1',
  name: 'นายสมชาย ใจดี',
  nickname: 'ก้อง',
  studentId: '45892',
  gradeRoom: 'ม.5/2',
  phone: '089-123-4567',
  promptPayNumber: '0891234567',
  role: 'STUDENT',
  avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
  isActive: true,
  joinedAt: '2026-05-15',
};

export const initialUsers: UserProfile[] = [
  {
    id: 'user_student_1',
    name: 'นายสมชาย ใจดี',
    nickname: 'ก้อง',
    studentId: '45892',
    gradeRoom: 'ม.5/2',
    phone: '089-123-4567',
    promptPayNumber: '0891234567',
    role: 'STUDENT',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    joinedAt: '2026-05-15',
  },
  {
    id: 'user_student_2',
    name: 'นางสาวณิชา พงษ์ไพศาล',
    nickname: 'แพรว',
    studentId: '45893',
    gradeRoom: 'ม.4/1',
    phone: '081-222-3344',
    promptPayNumber: '0812223344',
    role: 'STUDENT',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    joinedAt: '2026-05-16',
  },
  {
    id: 'user_student_3',
    name: 'นายธีรภัทร วัฒนา',
    nickname: 'ท็อป',
    studentId: '44210',
    gradeRoom: 'ม.6/3',
    phone: '089-998-8776',
    promptPayNumber: '0899988776',
    role: 'STUDENT',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    joinedAt: '2026-05-10',
  },
  {
    id: 'user_teacher_1',
    name: 'ครูศิริพร สุวรรณรัตน์',
    nickname: 'ครูผึ้ง',
    studentId: 'T-055',
    gradeRoom: 'หมวดวิทยาศาสตร์',
    phone: '084-555-1234',
    promptPayNumber: '0845551234',
    role: 'TEACHER',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    joinedAt: '2026-05-01',
  },
  {
    id: 'user_merchant_1',
    name: 'นางปราณี สุขใจ (ป้าณี)',
    nickname: 'ป้าณี',
    studentId: '-',
    gradeRoom: 'ผู้ประกอบการโรงอาหาร',
    phone: '081-987-6543',
    promptPayNumber: '0819876543',
    role: 'MERCHANT',
    shopId: 'shop_1',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    joinedAt: '2026-05-01',
  },
  {
    id: 'user_merchant_2',
    name: 'นายเอกชัย บุญช่วย (ลุงเอก)',
    nickname: 'ลุงเอก',
    studentId: '-',
    gradeRoom: 'ผู้ประกอบการโรงอาหาร',
    phone: '089-777-6655',
    promptPayNumber: '0897776655',
    role: 'MERCHANT',
    shopId: 'shop_2',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    joinedAt: '2026-05-02',
  },
  {
    id: 'user_admin_1',
    name: 'อาจารย์วิชัย เกียรติพิบูลย์',
    nickname: 'ครูวิชัย',
    studentId: 'T-102',
    gradeRoom: 'ฝ่ายบริหารงานโรงอาหาร / สภานักเรียน',
    phone: '086-555-8899',
    promptPayNumber: '0865558899',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    joinedAt: '2026-05-01',
  },
];

export const mockUsers: Record<string, UserProfile> = {
  student: initialUsers[0],
  merchant: initialUsers[4],
  admin: initialUsers[6],
};

export const initialSystemSettings: SystemSettings = {
  schoolName: 'โรงเรียนสรรพวิทยาคม (SorWor)',
  orderOpenTime: '06:00',
  orderCutoffTime: '20:00',
  pickupTimeWindow: '06:45 - 07:45 น.',
  maintenanceMode: false,
  emergencyBroadcast: '',
};

export const initialStalls: StallLocation[] = [
  { id: 'stall_1', code: 'STALL-01', name: 'ล็อก 1 (หน้าประตู 1 โซนข้าวแกง)', description: 'ใกล้ทางเข้าหลักโรงอาหาร' },
  { id: 'stall_2', code: 'STALL-02', name: 'ล็อก 2 (โซนข้าวแกงปักษ์ใต้ & อาหารจานด่วน)', description: 'ติดกับล็อก 1' },
  { id: 'stall_3', code: 'STALL-03', name: 'ล็อก 3 (โซนข้าวมันไก่ & ข้าวหมูกรอบ)', description: 'ตรงข้ามโต๊ะ ม.ปลาย' },
  { id: 'stall_4', code: 'STALL-04', name: 'ล็อก 4 (โซนอาหารตามสั่ง)', description: 'กลางโรงอาหาร' },
  { id: 'stall_5', code: 'STALL-05', name: 'ล็อก 5 (โซนก๋วยเตี๋ยวต้มยำ & บะหมี่)', description: 'ฝั่งเวทีประชาสัมพันธ์' },
  { id: 'stall_8', code: 'STALL-08', name: 'ล็อก 8 (โซนชานมไข่มุก & เบเกอรี่)', description: 'หัวมุมโรงอาหารฝั่งเสาธง' },
];

export const initialShops: Shop[] = [
  {
    id: 'shop_1',
    name: 'ร้านข้าวมันไก่ & ข้าวหมูกรอบ ป้าณี',
    ownerName: 'นางปราณี สุขใจ (ป้าณี)',
    stallId: 'stall_3',
    stallName: 'ล็อก 3 (โซนข้าวมันไก่ & ข้าวหมูกรอบ)',
    description: 'ข้าวมันไก่ตอนเนื้อนุ่ม หนังกรอบ น้ำจิ้มเต้าเจี้ยวรสเด็ด และข้าวหมูกรอบน้ำราดเข้มข้น ทำสดใหม่ทุกเช้า',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=1200&q=80',
    phone: '081-987-6543',
    promptPayNo: '0819876543',
    promptPayName: 'ปราณี สุขใจ (ป้าณีข้าวมันไก่)',
    cutoffTime: '20:30',
    isOpen: true,
    isApproved: true,
    registrationFeePaid: true,
    subscriptionExpiresAt: '2026-09-30T23:59:59Z',
    rating: 4.9,
    totalOrdersCount: 420,
  },
  {
    id: 'shop_2',
    name: 'ป้าแป๋ว ก๋วยเตี๋ยวต้มยำโบราณ & บะหมี่เกี๊ยว',
    ownerName: 'นางแป๋ว วงศ์สว่าง',
    stallId: 'stall_5',
    stallName: 'ล็อก 5 (โซนก๋วยเตี๋ยวต้มยำ & บะหมี่)',
    description: 'ก๋วยเตี๋ยวต้มยำมะนาวแท้ หมูสับแผ่นใหญ่ เกี๊ยวกรอบไม่อั้น พร้อมแยกน้ำซุปสำหรับเช้า',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=1200&q=80',
    phone: '089-444-1122',
    promptPayNo: '0894441122',
    promptPayName: 'แป๋ว วงศ์สว่าง (ป้าแป๋วก๋วยเตี๋ยว)',
    cutoffTime: '21:00',
    isOpen: true,
    isApproved: true,
    registrationFeePaid: true,
    subscriptionExpiresAt: '2026-09-15T23:59:59Z',
    rating: 4.8,
    totalOrdersCount: 310,
  },
  {
    id: 'shop_3',
    name: 'พี่กล้วย ชานมไข่มุก & โทสต์ปังเย็น',
    ownerName: 'นายกิตติศักดิ์ ชัยชนะ (พี่กล้วย)',
    stallId: 'stall_8',
    stallName: 'ล็อก 8 (โซนชานมไข่มุก & เบเกอรี่)',
    description: 'ชานมไต้หวันแท้ ไข่มุกหนึบหนับ ชาไทย ชาเขียวมัทฉะ และปังปิ้งเนยนมสด แยกน้ำแข็งพร้อมดื่มช่วงเช้า',
    imageUrl: 'https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=1200&q=80',
    phone: '095-777-3344',
    promptPayNo: '0957773344',
    promptPayName: 'กิตติศักดิ์ ชัยชนะ (พี่กล้วย ชานม)',
    cutoffTime: '22:00',
    isOpen: true,
    isApproved: true,
    registrationFeePaid: true,
    subscriptionExpiresAt: '2026-10-01T23:59:59Z',
    rating: 5.0,
    totalOrdersCount: 580,
  },
  {
    id: 'shop_4',
    name: 'ครัวลุงสมศักดิ์ ข้าวแกงปักษ์ใต้ & กับข้าวรสเด็ด',
    ownerName: 'นายสมศักดิ์ รัตนวิเชียร',
    stallId: 'stall_2',
    stallName: 'ล็อก 2 (โซนข้าวแกงปักษ์ใต้ & อาหารจานด่วน)',
    description: 'คั่วกลิ้งหมู, แกงส้มชะอมกุ้ง, หมูหวาน, ไข่พะโล้ และแกงเขียวหวานไก่ยอดมะพร้าว อร่อยจัดจ้าน',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    phone: '083-999-8877',
    promptPayNo: '0839998877',
    promptPayName: 'สมศักดิ์ รัตนวิเชียร (ครัวลุงสมศักดิ์)',
    cutoffTime: '20:00',
    isOpen: true,
    isApproved: true,
    registrationFeePaid: true,
    subscriptionExpiresAt: '2026-09-20T23:59:59Z',
    rating: 4.7,
    totalOrdersCount: 290,
  },
];

export const initialProducts: Product[] = [
  // Shop 1: ป้าณี
  {
    id: 'p_1_1',
    shopId: 'shop_1',
    name: 'ข้าวมันไก่ตอน (สูตรพิเศษ)',
    description: 'ไก่ตอนเนื้อฉ่ำ นุ่ม ไม่แห้ง พร้อมข้าวมันหอมกลมกล่อม น้ำซุปฟัก และน้ำจิ้มเต้าเจี้ยวพริกสด',
    basePrice: 40,
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400&q=80',
    category: 'rice',
    dailyQuota: 60,
    quotaRemaining: 18,
    isAvailable: true,
    optionGroups: [
      {
        id: 'og_size',
        title: 'ขนาด (Size)',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_normal', name: 'ธรรมดา', priceDelta: 0 },
          { id: 'opt_special', name: 'พิเศษ (เพิ่มเนื้อไก่)', priceDelta: 10 },
          { id: 'opt_jumbo', name: 'จัมโบ้ (ข้าว+ไก่ x2)', priceDelta: 20 },
        ],
      },
      {
        id: 'og_meat',
        title: 'ส่วนของเนื้อไก่',
        isRequired: false,
        minSelect: 0,
        maxSelect: 1,
        options: [
          { id: 'opt_breast', name: 'เนื้ออก (ไม่ติดมัน)', priceDelta: 0 },
          { id: 'opt_thigh', name: 'เนื้อน่อง/สะโพก (นุ่มฉ่ำ)', priceDelta: 0 },
          { id: 'opt_mix', name: 'รวมเนื้อ + เครื่องใน', priceDelta: 0 },
        ],
      },
      {
        id: 'og_addons',
        title: 'ตัวเลือกเพิ่มเติม',
        isRequired: false,
        minSelect: 0,
        maxSelect: 3,
        options: [
          { id: 'opt_egg_boiled', name: 'เพิ่มไข่ต้มยางมะตูม', priceDelta: 8 },
          { id: 'opt_egg_fried', name: 'เพิ่มไข่ดาวกรอบ', priceDelta: 10 },
          { id: 'opt_extra_skin', name: 'เพิ่มหนังไก่กรอบ', priceDelta: 5 },
          { id: 'opt_extra_sauce', name: 'แยกน้ำจิ้ม 2 ถ้วย', priceDelta: 0 },
        ],
      },
    ],
  },
  {
    id: 'p_1_2',
    shopId: 'shop_1',
    name: 'ข้าวมันไก่ทอดกรอบทอง',
    description: 'ไก่ทอดกรอบไม่อมน้ำมัน เสิร์ฟพร้อมน้ำจิ้มไก่หวานสูตรลับและน้ำซุปร้อนๆ',
    basePrice: 45,
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=400&q=80',
    category: 'rice',
    dailyQuota: 45,
    quotaRemaining: 9,
    isAvailable: true,
    optionGroups: [
      {
        id: 'og_size_fried',
        title: 'ขนาด',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_f_norm', name: 'ธรรมดา', priceDelta: 0 },
          { id: 'opt_f_spec', name: 'พิเศษ', priceDelta: 10 },
        ],
      },
      {
        id: 'og_addons_fried',
        title: 'เพิ่มท็อปปิ้ง',
        isRequired: false,
        minSelect: 0,
        maxSelect: 2,
        options: [
          { id: 'opt_add_egg', name: 'เพิ่มไข่ดาว', priceDelta: 10 },
          { id: 'opt_add_crispy', name: 'เพิ่มแป้งกรอบไม่อั้น', priceDelta: 5 },
        ],
      },
    ],
  },
  {
    id: 'p_1_3',
    shopId: 'shop_1',
    name: 'ข้าวหมูกรอบ & หมูแดงน้ำราดโบราณ',
    description: 'หมูกรอบหนังฟูกรอบสะท้านลิ้น หมูแดงหมักน้ำผึ้งฉ่ำๆ พร้อมไข่ต้มและกุนเชียง',
    basePrice: 50,
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=400&q=80',
    category: 'rice',
    dailyQuota: 40,
    quotaRemaining: 12,
    isAvailable: true,
    optionGroups: [
      {
        id: 'og_pork_type',
        title: 'เลือกประเภท',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_p_mix', name: 'หมูกรอบ + หมูแดง (รวม)', priceDelta: 0 },
          { id: 'opt_p_crispy_only', name: 'หมูกรอบล้วน', priceDelta: 5 },
          { id: 'opt_p_red_only', name: 'หมูแดงล้วน', priceDelta: 0 },
        ],
      },
      {
        id: 'og_pork_size',
        title: 'ขนาด',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_pk_norm', name: 'ธรรมดา', priceDelta: 0 },
          { id: 'opt_pk_spec', name: 'พิเศษ (เพิ่มเนื้อ)', priceDelta: 10 },
        ],
      },
    ],
  },

  // Shop 2: ป้าแป๋ว ก๋วยเตี๋ยว
  {
    id: 'p_2_1',
    shopId: 'shop_2',
    name: 'ก๋วยเตี๋ยวต้มยำมะนาวสดหมูสับแผ่น',
    description: 'ต้มยำพริกเผาคั่วเอง มะนาวแท้คั้นสด หมูสับแผ่นใหญ่ ลูกชิ้นปลา และเกี๊ยวกรอบ',
    basePrice: 40,
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=400&q=80',
    category: 'noodle',
    dailyQuota: 50,
    quotaRemaining: 22,
    isAvailable: true,
    optionGroups: [
      {
        id: 'og_noodle_type',
        title: 'เลือกเส้น (Noodle Type)',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_sen_lek', name: 'เส้นเล็กเหนียวนุ่ม', priceDelta: 0 },
          { id: 'opt_bami', name: 'บะหมี่ไข่เส้นแบน', priceDelta: 0 },
          { id: 'opt_sen_yai', name: 'เส้นใหญ่', priceDelta: 0 },
          { id: 'opt_sen_mee', name: 'เส้นหมี่ขาว', priceDelta: 0 },
          { id: 'opt_wun_sen', name: 'วุ้นเส้น', priceDelta: 5 },
          { id: 'opt_gao_lao', name: 'เกาเหลา (ไม่เอาเส้น)', priceDelta: 10 },
        ],
      },
      {
        id: 'og_noodle_soup',
        title: 'รูปแบบการเสิร์ฟ',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_soup', name: 'น้ำต้มยำ (แยกน้ำซุปให้)', priceDelta: 0 },
          { id: 'opt_dry', name: 'แห้งต้มยำ (คลุกพริกเผา + ซุปแยก)', priceDelta: 0 },
          { id: 'opt_clear', name: 'น้ำใส (ไม่เผ็ด)', priceDelta: 0 },
        ],
      },
      {
        id: 'og_noodle_addon',
        title: 'เพิ่มเครื่อง',
        isRequired: false,
        minSelect: 0,
        maxSelect: 3,
        options: [
          { id: 'opt_add_wonton', name: 'เกี๊ยวกรอบเพิ่ม 1 ถุง', priceDelta: 10 },
          { id: 'opt_add_egg_soft', name: 'ไข่ออนเซ็น 1 ฟอง', priceDelta: 10 },
          { id: 'opt_add_minced_pork', name: 'เพิ่มหมูสับแผ่นพิเศษ', priceDelta: 15 },
        ],
      },
    ],
  },
  {
    id: 'p_2_2',
    shopId: 'shop_2',
    name: 'บะหมี่เกี๊ยวหมูแดง & หมูกรอบ',
    description: 'บะหมี่ไข่เหนียวนุ่ม เกี๊ยวหมูเนื้อแน่นคำโต หมูแดงอบน้ำผึ้งและหมูกรอบ',
    basePrice: 45,
    imageUrl: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=400&q=80',
    category: 'noodle',
    dailyQuota: 35,
    quotaRemaining: 14,
    isAvailable: true,
    optionGroups: [
      {
        id: 'og_bm_style',
        title: 'รูปแบบ',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_bm_dry', name: 'บะหมี่แห้ง (แยกซุป)', priceDelta: 0 },
          { id: 'opt_bm_soup', name: 'บะหมี่น้ำใส', priceDelta: 0 },
          { id: 'opt_bm_tomyum', name: 'บะหมี่ต้มยำ', priceDelta: 5 },
        ],
      },
    ],
  },

  // Shop 3: พี่กล้วย ชานม & ปังเย็น
  {
    id: 'p_3_1',
    shopId: 'shop_3',
    name: 'ชานมไต้หวันพรีเมียม (Taiwan Milk Tea)',
    description: 'ใบชาคัดพิเศษ หอมละมุน กลมกล่อม ไม่แต่งกลิ่นสังเคราะห์ แยกน้ำแข็งให้พร้อมดื่มตอนเช้า',
    basePrice: 30,
    imageUrl: 'https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=400&q=80',
    category: 'drink',
    dailyQuota: 80,
    quotaRemaining: 34,
    isAvailable: true,
    optionGroups: [
      {
        id: 'og_sweetness',
        title: 'ระดับความหวาน (Sweetness)',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_sweet_0', name: 'ไม่หวานเลย (0%)', priceDelta: 0 },
          { id: 'opt_sweet_25', name: 'หวานน้อย (25%)', priceDelta: 0 },
          { id: 'opt_sweet_50', name: 'หวานกำลังดี (50%)', priceDelta: 0 },
          { id: 'opt_sweet_100', name: 'หวานปกติ (100%)', priceDelta: 0 },
        ],
      },
      {
        id: 'og_toppings',
        title: 'ท็อปปิ้ง (Toppings)',
        isRequired: false,
        minSelect: 0,
        maxSelect: 3,
        options: [
          { id: 'opt_boba', name: 'ไข่มุกบราวชูการ์หนึบ', priceDelta: 5 },
          { id: 'opt_jelly_grass', name: 'เฉาก๊วยหนึบหนับ', priceDelta: 5 },
          { id: 'opt_pudding', name: 'พุดดิ้งไข่นุ่มละมุน', priceDelta: 10 },
          { id: 'opt_cheese_foam', name: 'วิปชีสโฟมเข้มข้น', priceDelta: 15 },
        ],
      },
      {
        id: 'og_ice',
        title: 'การใส่น้ำแข็ง',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_ice_separate', name: 'แยกน้ำแข็งใส่ถุงให้ (แนะนำสำหรับสั่งเช้า)', priceDelta: 0 },
          { id: 'opt_ice_in_cup', name: 'ใส่น้ำแข็งในแก้วเลย', priceDelta: 0 },
          { id: 'opt_no_ice', name: 'ไม่เอาน้ำแข็ง (แช่เย็น)', priceDelta: 0 },
        ],
      },
    ],
  },
  {
    id: 'p_3_2',
    shopId: 'shop_3',
    name: 'ชาไทยโบราณการันตีความเข้มข้น',
    description: 'ชาไทยสีส้มทอง หอมกลิ่นชาคั่ว นมข้นหวานมันกำลังดี สูตรโรงเรียนสรรพวิทยาคม',
    basePrice: 25,
    imageUrl: 'https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=400&q=80',
    category: 'drink',
    dailyQuota: 70,
    quotaRemaining: 25,
    isAvailable: true,
    optionGroups: [
      {
        id: 'og_thai_sweet',
        title: 'ความหวาน',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_th_25', name: 'หวานน้อย', priceDelta: 0 },
          { id: 'opt_th_50', name: 'หวานปกติ', priceDelta: 0 },
          { id: 'opt_th_100', name: 'หวานเจี๊ยบ', priceDelta: 0 },
        ],
      },
      {
        id: 'og_thai_ice',
        title: 'น้ำแข็ง',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_th_sep', name: 'แยกน้ำแข็ง', priceDelta: 0 },
          { id: 'opt_th_in', name: 'ใส่น้ำแข็งในแก้ว', priceDelta: 0 },
        ],
      },
    ],
  },
  {
    id: 'p_3_3',
    shopId: 'shop_3',
    name: 'ปังปิ้งเนยนมน้ำตาลกรอบ (2 แผ่น)',
    description: 'ขนมปังหนานุ่ม ปิ้งเตาถ่านหอมกรุ่น ทาเนยสดแท้ ราดนมข้นเยิ้มๆ',
    basePrice: 25,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
    category: 'dessert',
    dailyQuota: 50,
    quotaRemaining: 30,
    isAvailable: true,
    optionGroups: [
      {
        id: 'og_toast_spread',
        title: 'เลือกหน้าปังปิ้ง',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_toast_milk', name: 'เนยนมน้ำตาล', priceDelta: 0 },
          { id: 'opt_toast_choco', name: 'ช็อกโกแลตนูเทลล่า', priceDelta: 5 },
          { id: 'opt_toast_sankaya', name: 'สังขยาใบเตยสด', priceDelta: 5 },
        ],
      },
    ],
  },

  // Shop 4: ครัวลุงสมศักดิ์ ข้าวแกง
  {
    id: 'p_4_1',
    shopId: 'shop_4',
    name: 'ข้าวราดแกง 2 อย่าง (เลือกกับข้าวได้)',
    description: 'ข้าวหอมมะลิร้อนๆ เลือกราดกับข้าวปักษ์ใต้หรือแกงภาคกลาง 2 อย่างตามใจชอบ',
    basePrice: 40,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=400&q=80',
    category: 'rice',
    dailyQuota: 45,
    quotaRemaining: 15,
    isAvailable: true,
    optionGroups: [
      {
        id: 'og_curry_1',
        title: 'กับข้าวอย่างที่ 1',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_c_kuakling', name: 'คั่วกลิ้งหมูสับ (เผ็ดร้อน)', priceDelta: 0 },
          { id: 'opt_c_sweetpork', name: 'หมูหวานสูตรใต้', priceDelta: 0 },
          { id: 'opt_c_greencurry', name: 'แกงเขียวหวานไก่ยอดมะพร้าว', priceDelta: 0 },
          { id: 'opt_c_palo', name: 'ไข่พะโล้หมูสามชั้น', priceDelta: 0 },
        ],
      },
      {
        id: 'og_curry_2',
        title: 'กับข้าวอย่างที่ 2',
        isRequired: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: 'opt_c2_sweetpork', name: 'หมูหวานสูตรใต้', priceDelta: 0 },
          { id: 'opt_c2_kuakling', name: 'คั่วกลิ้งหมูสับ', priceDelta: 0 },
          { id: 'opt_c2_chaom', name: 'แกงส้มชะอมไข่', priceDelta: 0 },
          { id: 'opt_c2_todu', name: 'ผัดกะเพราหมูสับ', priceDelta: 0 },
        ],
      },
      {
        id: 'og_curry_addon',
        title: 'เพิ่มไข่',
        isRequired: false,
        minSelect: 0,
        maxSelect: 1,
        options: [
          { id: 'opt_c_egg_fried', name: 'เพิ่มไข่ดาว', priceDelta: 10 },
          { id: 'opt_c_egg_omelet', name: 'เพิ่มไข่เจียวกรอบ', priceDelta: 10 },
        ],
      },
    ],
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ann_1',
    title: '🎉 ยินดีต้อนรับสู่ระบบ Sappha PreOrder!',
    subtitle: 'สั่งวันนี้ รับพรุ่งนี้เช้า 06:45 - 07:45 น. สะดวก ไม่ต้องต่อคิว',
    content: 'เปิดให้บริการแล้วสำหรับนักเรียน ครู และบุคลากรโรงเรียนสรรพวิทยาคม สั่งล่วงหน้าและชำระเงินผ่าน PromptPay ได้เลย!',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    badgeText: 'ข่าวประชาสัมพันธ์',
    isActive: true,
  },
  {
    id: 'ann_2',
    title: '⭐ เมนูแนะนำสัปดาห์นี้: ข้าวมันไก่ตอนป้าณี & ชานมพี่กล้วย',
    subtitle: 'รีวิวแน่น ยอดสั่งทะลุโควตาทุกวัน อย่าลืมสั่งก่อนตัดรอบ 20:30 น.',
    content: 'ข้าวมันไก่ตอนเนื้อนุ่มจิ้มน้ำจิ้มสูตรเด็ด คู่กับชานมไข่มุกแยกน้ำแข็ง เติมพลังมื้อเช้าก่อนเข้าแถวเคารพธงชาติ',
    imageUrl: 'https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=1200&q=80',
    badgeText: 'เมนูฮิต',
    isActive: true,
  },
];

export const initialHolidays: SchoolHoliday[] = [
  { id: 'h_1', date: '2026-08-12', name: 'วันเฉลิมพระชนมพรรษา สมเด็จพระบรมราชชนนีพันปีหลวง (วันแม่แห่งชาติ)', isLocked: true },
  { id: 'h_2', date: '2026-10-13', name: 'วันนวมินทรมหาราช', isLocked: true },
  { id: 'h_3', date: '2026-10-23', name: 'วันปิยมหาราช', isLocked: true },
];

export const initialOrders: Order[] = [
  {
    id: 'order_1000',
    orderCode: 'SW-1208',
    pickupCode4Digits: '1208',
    userId: 'user_student_1',
    userName: 'นายสมชาย ใจดี',
    userNickname: 'ก้อง',
    userGradeRoom: 'ม.5/2',
    userStudentId: '45892',
    userPhone: '089-123-4567',
    shopId: 'shop_1',
    shopName: 'ร้านข้าวมันไก่ & ข้าวหมูกรอบ ป้าณี',
    stallName: 'ล็อก 3 (โซนข้าวมันไก่ & ข้าวหมูกรอบ)',
    pickupDate: 'วันนี้',
    pickupTimeWindow: '06:45 - 07:45 น.',
    subtotal: 40,
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    reviewed: false,
    paymentSlip: {
      slipUrl: 'https://images.unsplash.com/photo-1580048915913-4f8f5cb481c4?auto=format&fit=crop&w=600&q=80',
      amount: 40,
      uploadedAt: new Date(Date.now() - 86400000).toISOString(),
      status: 'APPROVED',
    },
    items: [
      {
        id: 'oi_0',
        productId: 'p_1_1',
        productName: 'ข้าวมันไก่ตอน (สูตรพิเศษ)',
        quantity: 1,
        unitPrice: 40,
        totalPrice: 40,
        selectedOptions: [
          { groupId: 'og_size', groupTitle: 'ขนาด', itemId: 'opt_normal', itemName: 'ธรรมดา', priceDelta: 0 },
        ],
      },
    ],
  },
  {
    id: 'order_1001',
    orderCode: 'SW-4089',
    pickupCode4Digits: '4089',
    userId: 'user_student_1',
    userName: 'นายสมชาย ใจดี',
    userNickname: 'ก้อง',
    userGradeRoom: 'ม.5/2',
    userStudentId: '45892',
    userPhone: '089-123-4567',
    shopId: 'shop_1',
    shopName: 'ร้านข้าวมันไก่ & ข้าวหมูกรอบ ป้าณี',
    stallName: 'ล็อก 3 (โซนข้าวมันไก่ & ข้าวหมูกรอบ)',
    pickupDate: 'พรุ่งนี้เช้า',
    pickupTimeWindow: '06:45 - 07:45 น.',
    subtotal: 50,
    status: 'CONFIRMED',
    createdAt: new Date().toISOString(),
    paymentSlip: {
      slipUrl: 'https://images.unsplash.com/photo-1580048915913-4f8f5cb481c4?auto=format&fit=crop&w=600&q=80',
      amount: 50,
      uploadedAt: new Date().toISOString(),
      status: 'APPROVED',
    },
    items: [
      {
        id: 'oi_1',
        productId: 'p_1_1',
        productName: 'ข้าวมันไก่ตอน (สูตรพิเศษ)',
        quantity: 1,
        unitPrice: 50,
        totalPrice: 50,
        selectedOptions: [
          { groupId: 'og_size', groupTitle: 'ขนาด', itemId: 'opt_special', itemName: 'พิเศษ', priceDelta: 10 },
          { groupId: 'og_meat', groupTitle: 'ส่วนของเนื้อไก่', itemId: 'opt_thigh', itemName: 'เนื้อน่อง/สะโพก', priceDelta: 0 },
        ],
        specialInstructions: 'ขอแตงกวาเยอะๆ ครับ ไม่เอากระเทียมเจียว',
      },
    ],
  },
  {
    id: 'order_1002',
    orderCode: 'SW-8120',
    pickupCode4Digits: '8120',
    userId: 'user_student_1',
    userName: 'นายสมชาย ใจดี',
    userNickname: 'ก้อง',
    userGradeRoom: 'ม.5/2',
    userStudentId: '45892',
    userPhone: '089-123-4567',
    shopId: 'shop_3',
    shopName: 'พี่กล้วย ชานมไข่มุก & โทสต์ปังเย็น',
    stallName: 'ล็อก 8 (โซนชานมไข่มุก & เบเกอรี่)',
    pickupDate: 'พรุ่งนี้เช้า',
    pickupTimeWindow: '06:45 - 07:45 น.',
    subtotal: 35,
    status: 'PENDING_APPROVAL',
    createdAt: new Date().toISOString(),
    paymentSlip: {
      slipUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
      amount: 35,
      uploadedAt: new Date().toISOString(),
      status: 'PENDING',
    },
    items: [
      {
        id: 'oi_2',
        productId: 'p_3_1',
        productName: 'ชานมไต้หวันพรีเมียม',
        quantity: 1,
        unitPrice: 35,
        totalPrice: 35,
        selectedOptions: [
          { groupId: 'og_sweetness', groupTitle: 'ความหวาน', itemId: 'opt_sweet_50', itemName: 'หวานกำลังดี (50%)', priceDelta: 0 },
          { groupId: 'og_toppings', groupTitle: 'ท็อปปิ้ง', itemId: 'opt_boba', itemName: 'ไข่มุกบราวชูการ์หนึบ', priceDelta: 5 },
          { groupId: 'og_ice', groupTitle: 'การใส่น้ำแข็ง', itemId: 'opt_ice_separate', itemName: 'แยกน้ำแข็งใส่ถุงให้', priceDelta: 0 },
        ],
      },
    ],
  },
];

export const initialFeeRecords: MerchantFeeRecord[] = [
  {
    id: 'fee_1',
    shopId: 'shop_1',
    shopName: 'ร้านข้าวมันไก่ & ข้าวหมูกรอบ ป้าณี',
    type: 'REGISTRATION',
    amount: 20,
    paidAt: '2026-08-01T10:00:00Z',
    note: 'ชำระค่าแรกเข้าเปิดร้านค้า',
  },
  {
    id: 'fee_2',
    shopId: 'shop_1',
    shopName: 'ร้านข้าวมันไก่ & ข้าวหมูกรอบ ป้าณี',
    type: 'MONTHLY',
    amount: 20,
    paidAt: '2026-08-01T10:00:00Z',
    validUntil: '2026-09-30T23:59:59Z',
    note: 'ค่าบำรุงรักษาระบบรายเดือน ประจำเดือนสิงหาคม-กันยายน 2569',
  },
  {
    id: 'fee_3',
    shopId: 'shop_2',
    shopName: 'ป้าแป๋ว ก๋วยเตี๋ยวต้มยำโบราณ & บะหมี่เกี๊ยว',
    type: 'REGISTRATION',
    amount: 20,
    paidAt: '2026-08-05T14:30:00Z',
    note: 'ชำระค่าแรกเข้าเปิดร้านค้า',
  },
  {
    id: 'fee_4',
    shopId: 'shop_3',
    shopName: 'พี่กล้วย ชานมไข่มุก & โทสต์ปังเย็น',
    type: 'REGISTRATION',
    amount: 20,
    paidAt: '2026-08-10T09:15:00Z',
    note: 'ชำระค่าแรกเข้าเปิดร้านค้า',
  },
];

export const initialReviews: ShopReview[] = [
  {
    id: 'rev_1',
    orderId: 'order_mock_1',
    shopId: 'shop_1',
    userId: 'user_student_2',
    userName: 'นางสาวณิชา พงษ์ไพศาล',
    userNickname: 'แพรว',
    userGradeRoom: 'ม.4/1',
    rating: 5,
    comment: 'ข้าวมันไก่ป้าณีอร่อยมากกก ข้าวมันหอม น้ำจิ้มเต้าเจี้ยวคือเดอะเบสต์ในโรงอาหาร สั่งรอบที่ 5 แล้วค่ะ!',
    isAnonymous: false,
    createdAt: '2026-08-16T08:15:00Z',
  },
  {
    id: 'rev_2',
    orderId: 'order_mock_2',
    shopId: 'shop_1',
    userId: 'user_student_3',
    userName: 'นายธีรภัทร วัฒนา',
    userNickname: 'ท็อป',
    userGradeRoom: 'ม.6/3',
    rating: 5,
    comment: 'ข้าวหมูกรอบหนังฟูกรอบมาก น้ำราดเข้มข้นไม่หวานเกินไป ให้เยอะอิ่มถึงเที่ยงเลยครับ 👍',
    isAnonymous: false,
    createdAt: '2026-08-17T07:50:00Z',
  },
  {
    id: 'rev_3',
    orderId: 'order_mock_3',
    shopId: 'shop_1',
    userId: 'user_student_anon',
    userName: 'นักเรียนสรรพวิทยาคม',
    userNickname: 'นักเรียน',
    userGradeRoom: 'ม.5',
    rating: 4,
    comment: 'อร่อย สะดวกรวดเร็ว ไม่ต้องยืนต่อคิวนานตอนเช้าเลยครับ เดินมารับปุ๊บได้ปั๊บ',
    isAnonymous: true,
    createdAt: '2026-08-17T08:00:00Z',
  },
  {
    id: 'rev_4',
    orderId: 'order_mock_4',
    shopId: 'shop_3',
    userId: 'user_student_2',
    userName: 'นางสาวณิชา พงษ์ไพศาล',
    userNickname: 'แพรว',
    userGradeRoom: 'ม.4/1',
    rating: 5,
    comment: 'ชานมไต้หวันสั่งหวาน 50% กำลังฟิน ไข่มุกนุ่มหนึบมากก แก้วใหญ่สะใจ 🧋✨',
    isAnonymous: false,
    createdAt: '2026-08-17T08:05:00Z',
  },
  {
    id: 'rev_5',
    orderId: 'order_mock_5',
    shopId: 'shop_2',
    userId: 'user_student_3',
    userName: 'นายธีรภัทร วัฒนา',
    userNickname: 'ท็อป',
    userGradeRoom: 'ม.6/3',
    rating: 5,
    comment: 'ต้มยำป้าแป๋วแซ่บจริงจัง หมูเด้งแผ่นใหญ่ เกี๊ยวกรอบไม่อมน้ำมัน แนะนำเลย!',
    isAnonymous: false,
    createdAt: '2026-08-16T08:30:00Z',
  },
];
